In [1]:
import pandas as pd
import requests

In [30]:
from io import StringIO

## Fetching Data using Rapid API site which provides several APIs

 I fetch this data from Visual Crossing Weather's API with the help of Rapid API and then I processed it according to my requirement and automate the task of fetching the data between two certain dates using python and then I export that into a CSV.

In [102]:
import datetime
start = datetime.date(2017,1,1)
end = datetime.date(2018,12,31)
df = pd.DataFrame()
while start < end:
    url = "https://visual-crossing-weather.p.rapidapi.com/history"
    headers = {
            "X-RapidAPI-Key": "e0089e0c2emsh0bebbd1bc5341b2p1042d6jsn3e48e26fe9c4",
            "X-RapidAPI-Host": "visual-crossing-weather.p.rapidapi.com"
        } # provide your own X-RapidAPI-Key and X-RapidAPI-Host from rapid api site - Visual Crossing Weather
    if end > start + datetime.timedelta(29):
        
        start_date = start
        start_str = str(start_date) + 'T00:00:00'
        End_date = start_date + datetime.timedelta(29) # as this api gives only 30 days' data in a single request, so I made the end date according to that rule.
        End_str =  str(End_date) + 'T00:00:00'
        querystring = {f"startDateTime":{start_str},"aggregateHours":"24","location":"Kolkata,West Bengal,India","endDateTime":{End_str},"unitGroup":"uk","contentType":"csv","shortColumnNames":"0"}
    else:
        start_date = start
        start_str = str(start_date) + 'T00:00:00'
        End_date = end
        End_str =  str(End_date) + 'T00:00:00'
        querystring = {f"startDateTime":{start_str},"aggregateHours":"24","location":"Kolkata,West Bengal,India","endDateTime":{End_str},"unitGroup":"uk","contentType":"csv","shortColumnNames":"0"}
    response = requests.request("GET", url, headers=headers, params=querystring)
    temp_df = pd.read_csv(StringIO(response.text)) # made that reponse text into a comma separated value and then it was turned into a data frame.
    df = df.append(temp_df, ignore_index= True) # merge those every response's data to make a single data frame.
    start = End_date + datetime.timedelta(1)

In [105]:
five_years_weather_data = df

In [106]:
five_years_weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              1826 non-null   object
 1   Date time            1826 non-null   object
 2   Minimum Temperature  1826 non-null   float64
 3   Maximum Temperature  1826 non-null   float64
 4   Temperature          1826 non-null   float64
 5   Dew Point            1826 non-null   float64
 6   Relative Humidity    1826 non-null   float64
 7   Heat Index           1538 non-null   float64
 8   Wind Speed           1826 non-null   float64
 9   Wind Gust            54 non-null     float64
 10  Wind Direction       1826 non-null   float64
 11  Wind Chill           13 non-null     float64
 12  Precipitation        1826 non-null   float64
 13  Precipitation Cover  1826 non-null   float64
 14  Snow Depth           1826 non-null   float64
 15  Visibility           1826 non-null   float64
 16  Cloud Cover          1826 non-null   float64
 17  Sea Level Pressure   1825 non-null   float64
 18  Weather Type         1825 non-null   object
 19  Latitude             1826 non-null   float64
 20  Longitude            1826 non-null   float64
 21  Resolved Address     1826 non-null   object
 22  Name                 1826 non-null   object
 23  Info                 0 non-null      float64
 24  Conditions           1826 non-null   object
dtypes: float64(19), object(6)
memory usage: 356.8+ KB

In [107]:
five_years_weather_data.sample(10)

,Address,Date time,Minimum Temperature,Maximum Temperature,Temperature,Dew Point,Relative Humidity,Heat Index,Wind Speed,Wind Gust,...,Visibility,Cloud Cover,Sea Level Pressure,Weather Type,Latitude,Longitude,Resolved Address,Name,Info,Conditions
1466,"Kolkata,West Bengal,India",01/06/2021,16.8,29.2,22.7,16.2,69.08,29.6,5.8,NaN,...,1.7,0.0,1012.4,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear
165,"Kolkata,West Bengal,India",06/15/2017,28.0,34.5,30.7,25.9,76.39,45.3,11.4,NaN,...,2.5,50.0,1001.4,"Thunderstorm Without Precipitation, Sky Unchan...",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,"Rain, Partially cloudy"
776,"Kolkata,West Bengal,India",02/16/2019,19.0,28.0,22.3,15.9,68.25,28.3,11.4,NaN,...,2.1,36.3,1014.3,"Mist, Light Rain, Sky Coverage Increasing, Smo...",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Partially cloudy
696,"Kolkata,West Bengal,India",11/28/2018,19.0,29.4,23.2,16.4,68.38,29.1,4.7,NaN,...,2.0,45.7,1016.2,"Mist, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Partially cloudy
570,"Kolkata,West Bengal,India",07/25/2018,27.0,32.0,28.4,26.6,89.87,42.4,10.3,NaN,...,1.9,87.4,1000.6,"Light Drizzle, Thunderstorm, Light Rain, Sky C...",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,"Rain, Overcast"
354,"Kolkata,West Bengal,India",12/21/2017,14.0,23.0,17.9,14.6,81.50,NaN,5.8,NaN,...,1.3,16.0,1018.0,"Mist, Sky Coverage Increasing, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear
992,"Kolkata,West Bengal,India",09/20/2019,27.6,35.0,30.1,27.0,83.94,47.3,13.9,NaN,...,2.3,54.0,1008.3,"Thunderstorm, Thunderstorm Without Precipitati...",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,"Rain, Partially cloudy"
1213,"Kolkata,West Bengal,India",04/28/2020,23.0,26.7,24.9,23.5,92.12,NaN,10.3,NaN,...,1.9,68.6,1010.5,"Mist, Light Drizzle, Thunderstorm, Rain, Thund...",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,"Rain, Partially cloudy"
1476,"Kolkata,West Bengal,India",01/16/2021,14.0,23.1,17.6,13.6,78.18,NaN,6.9,NaN,...,1.2,0.0,1012.0,"Mist, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Clear
49,"Kolkata,West Bengal,India",02/19/2017,20.0,30.0,25.0,20.1,75.61,31.9,6.9,NaN,...,1.7,35.2,1012.4,"Mist, Fog, Smoke Or Haze",22.5705,88.3713,"Kolkata, WB, India","Kolkata, WB, India",NaN,Partially cloudy

In [109]:
five_years_weather_data.to_csv('fiveyearsweatherdata.csv', index= False)